### ISSUE TITLE
pull google sheets enrollment info into raw

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/Raw-Database#1]

**Comment by saseehav** [comment]
I feel like we went away from pulling google sheets 2020 into the Raw, during dataflow.  @aureliemponcet did you say that it's best to pull into the production database directly?

**Comment by screberg** [comment]
My understanding was that in future iterations, tech dashboard directly edits production database.  But with google sheets, we will put this into Raw

**Comment by aureliemponcet** [comment]
@screberg @saseehav  I will import the 2020 enrollment data directly into the production database and pre-populate all data tables. We agreed during the data flow meeting that no google sheet data is going into the Raw database.

**Comment by screberg** [comment]
Got it.  Thanks Sarah and Aurelie for having better memories than this old man.
